config/routes.rb
Rails.application.routes.draw do
  resources:students
  resources:teachers
  resources:exams
  resources:reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/laporan.rb
class Laporan < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    
        def new
            @exam = Exam.new  
          end
      
          def create
              exam= Exam.new(resource_params)
              exam.save
              flash[:notice] = 'exam has been created'
              #puts book.errors.messages
              redirect_to exams_path
          end
      
          def edit
              @exam = Exam.find(params[:id])
          end
      
          def update
              @exam = Exam.find(params[:id])
              @exam.update(resource_params)
              flash[:notice] = 'exam has been update'
              redirect_to edit_exam_path(@exam)
          end
          def destroy
           @exam = Exam.find(params[:id])
           @exam.destroy
            flash[:notice] = 'Exam has been deleted'
            redirect_to exams_path
        end
    
        def index
           @exam = Exam.all
        end
    
        def show #menampilkan secaraa detail
            id = params[:id]
           @exam = Exam.find(id)
            # render plain: id
            # render plain: @book.title
        end
    
        private
    
        def resource_params
            params.require(:exam).permit(:title, :mapel, :duration, :nilai, :akatif, :level, :student_id)
        end
    

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
        def new
            @report = Report.new  
          end
      
          def create
              report= Report.new(resource_params)
              report.save
              flash[:notice] = 'Report has been created'
              #puts book.errors.messages
              redirect_to reports_path
          end
      
          def edit
              @report = Report.find(params[:id])
          end
      
          def update
              @report = Report.find(params[:id])
              @report.update(resource_params)
              flash[:notice] = 'Report has been update'
              redirect_to reports_path(@report)
          end
          def destroy
           @report = Report.find(params[:id])
           @report.destroy
            flash[:notice] = 'Report has been deleted'
            redirect_to reports_path
        end
    
        def index
           @report = Report.all
        end
    
        def show #menampilkan secaraa detail
            id = params[:id]
           @report = Report.find(id)
            # render plain: id
            # render plain: @book.title
        end
    
        private
    
        def resource_params
            params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id)
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new
        @student = Student.new  
      end
  
      def create
          student = Student.new(resource_params)
          student.save
          flash[:notice] = 'Student has been created'
          #puts book.errors.messages
          redirect_to students_path
      end
  
      def edit
          @student = Student.find(params[:id])
      end
  
      def update
          @student = Student.find(params[:id])
          @student.update(resource_params)
          flash[:notice] = 'Student has been update'
          redirect_to edit_student_path(@student)
      end
      def destroy
        @student = Student.find(params[:id])
        @student.destroy
        flash[:notice] = 'Book has been deleted'
        redirect_to students_path
    end

    def index
        @student = Student.all
    end

    def show #menampilkan secaraa detail
        id = params[:id]
        @student = Student.find(id)
        # render plain: id
        # render plain: @book.title
    end

    private

    def resource_params
        params.require(:student).permit(:name, :username, :age, :kelas, :addres, :city, :nik)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
        def new
            @teacher = Teacher.new  
          end
      
          def create
              teacher = Teacher.new(resource_params)
              teacher.save
              flash[:notice] = 'Student has been created'
              #puts book.errors.messages
              redirect_to teachers_path
          end
      
          def edit
              @teacher = Teacher.find(params[:id])
          end
      
          def update
              @teacher = Teacher.find(params[:id])
              @teacher.update(resource_params)
              flash[:notice] = 'Teacher has been update'
              redirect_to teachers_path(@teacher)
          end
          def destroy
            @teacher = Teacher.find(params[:id])
            @teacher.destroy
            flash[:notice] = 'teacher has been deleted'
            redirect_to teachers_path
        end
    
        def index
            @teacher = Teacher.all
        end
    
        def show #menampilkan secaraa detail
            id = params[:id]
            @teacher = Teacher.find(id)
            # render plain: id
            # render plain: @book.title
        end
    
        private
    
        def resource_params
            params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
        end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   
   <br> 
<%= link_to 'Back', exams_path, class: "btn btn-primary"%>
<div class="container-md">
<div class="card" style="width: 40rem;">
 

  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">Edit Exam</h6>
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title, class: "form-control"%> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class: "form-control"%> </br>

    <%= f.label :duration%> </br>
    <%= f.text_field :duration, class: "form-control"%> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai, class: "form-control"%> </br>

    <%= f.label :aktif %> </br>
    <%= f.text_field :aktif, class: "form-control"%> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level, class: "form-control"%> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id, class: "form-control"%> </br>

    <%= f.submit %>
    
    </div>
    </div>

<% end %>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/exams/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      
        
        
        index
        <% if flash[:notice].present? %>
        <%= flash[:notice] %>
        <% end %> </br>
        <div class="container">
        <table class="table">
        <tr>
        <td>Title</td>
        <td>Mapel</td>
        <td>Duration</td>
        <td>Action</td>
        </tr>

        <% @exam.each do |exam| %>
            <tr>
            <td><%= exam.title%></td>
            <td><%= exam.mapel %></td>
            <td><%= exam.duration %></td>
            <td>
            <%= link_to 'Detail', exam_path(exam), class: "btn btn-info" %>
            <%= link_to 'Edit', edit_exam_path(exam), class: "btn btn-warning" %> 
            <%= link_to 'Delete', exam_path(exam), class: "btn btn-danger", method: :delete, data:{confirm: 'Are you sure?'} %></td>
            </tr>
    <% end %>
    </table>
   <div class="pull-right">         
    <%= link_to 'New Exam', new_exam_path, class: "btn btn-primary"%>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/exams/new.html.erb
<!doctype html>
<html lang="en">
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
<div class="container-md">
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">New Exam</h6>
<meta charset="UTF-9">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title, class: "form-control" %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel, class: "form-control" %> </br>

    <%= f.label :duration%> </br>
    <%= f.text_field :duration, class: "form-control"%> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai, class: "form-control" %> </br>

    <%= f.label :aktif %> </br>
    <%= f.text_field :aktif, class: "form-control" %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level, class: "form-control" %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id, class: "form-control"%> </br>



    <%= f.submit %>
    <%= link_to 'Back', exams_path, class: "btn btn-info"%>
<% end %>
</div>
</div>

app/views/exams/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="container-md">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">Detail Exam</h6>
        <% if flash[:notice].present? %>
            <%= flash[:notice] %>
            <% end %> </br>
            Title : <%= @exam.title %> </br>
            Mapel : <%= @exam.mapel%> </br>
            Duration : <%= @exam.duration %> </br>
            Nilai : <%= @exam.nilai %> </br>
            <%= link_to 'Back', exams_path%>
  </div>
</div>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kejarid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
<div class="container-md">
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">New Student</h6>
<meta charset="UTF-9">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<%= form_for(@report) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title, class: "form-control" %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil, class: "form-control" %> </br>

    <%= f.label :mapel%> </br>
    <%= f.text_field :mapel, class: "form-control"%> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id, class: "form-control" %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id, class: "form-control" %> </br>

    <%= f.submit %>
    <%= link_to 'Back', reports_path, class: "btn btn-info" %>
<% end %>
</div>
</div>

app/views/reports/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
index
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<div class="container">
<table class="table"   class="md-4">

<tr>
<td>Title</td>
<td>Hasil</td>
<td>Maple</td>
<td> Action</td>
</tr>

<% @report.each do |report| %>
    <tr>
    <td><%= report.title%></td>
    <td><%= report.hasil %></td>
    <td><%= report.mapel %></td>
    <td>
    <div class="pull-right">
    <%= link_to 'Detail', report_path(report), class: "btn btn-info" %>
    <%= link_to 'Edit', edit_report_path(report), class: "btn btn-warning" %> 
    <%= link_to 'Delete', report_path(report), class: "btn btn-danger", method: :delete, data:{confirm: 'Are you sure?'} %>
    </div>
    </td>
    </tr>
    <% end %>
    </table>

    <%= link_to 'New Exam', new_report_path, class: "btn btn-primary" %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </html>

app/views/students/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<div class="container">
<table class="table"   class="md-4">
<tr>
<td>Name</td>
<td>Username</td>
<td>Age</td>
<td>Action</td>
</tr>

<% @student.each do |student| %>
    <tr>
    <td><%= student.name%></td>
    <td><%= student.username %></td>
    <td><%= student.age %></td>
    <td>
    <div class="pull-right">
    <%= link_to 'Detail', student_path(student), class: "btn btn-info" %>
    <%= link_to 'Edit', edit_student_path(student), class: "btn btn-warning" %> 
 <%= link_to 'Delete', student_path(student), class: "btn btn-danger", method: :delete, data:{confirm: 'Are you sure?'} %>
 </div>
 </td>
    </tr>
    <% end %>
    </table>
    <div class="pull-right">
    <%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </html>

app/views/teachers/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<h3> Index</h3>
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<div class="container">
<table class="table"   class="md-4">
<td><b>Nik</td>
<td><b>Name</td>
<td><b>Age</td>
<td><b>Rombel</td>
<td><b>Mapel</td>
<td colspan="3"><b>Action</td>
</tr>

<% @teacher.each do |teacher| %>
    <tr>
    <td><%= teacher.nik%></td>
    <td><%= teacher.name %></td>
    <td><%= teacher.age %></th>
    <td><%= teacher.kelas %></th>
    <td><%= teacher.mapel %></th>
    
    <td>
    <div class="pull-right">
     <%= link_to 'Detail', teacher_path(teacher), class: "btn btn-info"%>
     <%= link_to 'Edit', edit_teacher_path(teacher), class: "btn btn-warning"%> 
     <%= link_to 'Delete', teacher_path(teacher), class: "btn btn-danger", method: :delete, data:{confirm: 'Are you sure?'} %>
     </td>
     </div>
    </tr>

    <% end %>
    </table>


<div class="pull-right">
    <%= link_to 'New Student', new_teacher_path, class: "btn btn-primary"%>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </html>